# Generated by Django 5.1.3 on 2024-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_personalinfo_description_personalinfo_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
