# Generated by Django 5.1.3 on 2025-01-03 17:43
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="LegalAndPrivacy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("title_en", models.CharField(max_length=100, null=True, unique=True)),
                ("title_es", models.CharField(max_length=100, null=True, unique=True)),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_es", models.TextField(null=True)),
            ],
        ),
    )
