# Generated by Django 5.1.4 on 2025-01-15 11:33
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("base", "0002_followmelink"),
        ("cookie_consent", "0002_cookiegroup_version"),
    )

    operations = (
        migrations.CreateModel(
            name="GoogleAnalytics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("use_analytics", models.BooleanField(default=False)),
                ("gtag", models.CharField(blank=True, max_length=20)),
                ("debug_mode", models.BooleanField(default=False)),
                (
                    "cookie_consent",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.RESTRICT, to="cookie_consent.cookiegroup"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    )
