# Generated by Django 5.1.5 on 2025-01-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("base", "0003_googleanalytics"),
        ("cooco", "0001_initial"),
        ("cookie_consent", "0004_delete_bannerconfig_delete_cookiegroup"),
    )

    operations = (
        migrations.AlterField(
            model_name="googleanalytics",
            name="cookie_consent",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to="cooco.cookiegroup"),
        ),
    )
