# Generated by Django 5.2.15 on 2026-06-14 16:46
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("base", "0004_alter_googleanalytics_cookie_consent"),)

    operations = (
        migrations.CreateModel(
            name="SiteMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "background_image",
                    models.ImageField(
                        default="site/background.jpg",
                        help_text="Recommended aspect ratio as close as possible to 16:9, with a minimum "
                        "size of 1920x1080px. Also used, cropped to 1200x630 for the Open Graph preview "
                        "and 1200x675 for the Twitter preview.",
                        upload_to="site/",
                    ),
                ),
                ("favicon", models.ImageField(default="site/favicon.ico", upload_to="site/")),
                ("logo", models.ImageField(default="site/icon.png", upload_to="site/")),
            ],
            options={
                "abstract": False,
            },
        ),
    )
