from __future__ import annotations

# Generated by Django 5.2.15 on 2026-06-17 12:27
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("base", "0005_sitemedia"),)

    operations = (
        migrations.RenameField(
            model_name="sitemedia",
            old_name="background_image",
            new_name="portrait_image",
        ),
        migrations.AlterField(
            model_name="sitemedia",
            name="portrait_image",
            field=models.ImageField(
                default="site/portrait.png",
                help_text="16:9 image with the subject centered (used for hero portrait and social media "
                "previews: 1200x630 OG, 1200x675 Twitter). Minimum recommended size: 1920x1080px.",
                upload_to="site/",
            ),
        ),
    )
