# Generated by Django 5.1.3 on 2024-11-12 08:48
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0001_initial"),)

    operations = (
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    )
