# Generated by Django 5.1.3 on 2024-11-21 16:20
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0003_experience_description_en_experience_description_es_and_more"),)

    operations = (
        migrations.AddField(
            model_name="personalinfo",
            name="description",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="description_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="description_es",
            field=models.CharField(max_length=100, null=True),
        ),
    )
