# Generated by Django 5.1.7 on 2025-03-26 09:10
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0005_alter_experience_end_date"),)

    operations = (
        migrations.RenameField(
            model_name="personalinfo",
            old_name="description",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="personalinfo",
            old_name="description_en",
            new_name="title_en",
        ),
        migrations.RenameField(
            model_name="personalinfo",
            old_name="description_es",
            new_name="title_es",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="introduction",
            field=models.TextField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="introduction_en",
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="introduction_es",
            field=models.TextField(max_length=500, null=True),
        ),
    )
