# Generated by Django 5.2.8 on 2025-12-28 17:22
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0006_rename_description_personalinfo_title_and_more"),)

    operations = (
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_es", models.CharField(max_length=100, null=True, unique=True)),
                ("priority", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Technologies",
                "ordering": ("priority", "name"),
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="technologies",
            field=models.ManyToManyField(blank=True, related_name="experiences", to="home.technology"),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="technologies",
            field=models.ManyToManyField(blank=True, related_name="personal_info", to="home.technology"),
        ),
    )
