# Generated by Django 5.2.8 on 2025-12-28 20:27
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0007_technology_experience_technologies_and_more"),)

    operations = (
        migrations.AlterField(
            model_name="experience",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="SubProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("client", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sub_projects", to="home.experience"
                    ),
                ),
                ("technologies", models.ManyToManyField(blank=True, related_name="sub_projects", to="home.technology")),
            ],
            options={
                "ordering": ("-start_date",),
            },
        ),
    )
