# Generated by Django 5.2.8 on 2026-01-02 16:25
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0008_alter_experience_company_subproject"),)

    operations = (
        migrations.CreateModel(
            name="Education",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_es", models.CharField(max_length=200, null=True)),
                ("institution", models.CharField(max_length=200)),
                ("institution_en", models.CharField(max_length=200, null=True)),
                ("institution_es", models.CharField(max_length=200, null=True)),
                ("location", models.CharField(max_length=200)),
                ("location_en", models.CharField(max_length=200, null=True)),
                ("location_es", models.CharField(max_length=200, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
            ],
            options={
                "verbose_name_plural": "Education entries",
            },
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="company",
            new_name="institution",
        ),
        migrations.AlterField(
            model_name="experience",
            name="institution",
            field=models.CharField(blank=True, max_length=200, verbose_name="Company"),
        ),
    )
