# Generated by Django 5.2.15 on 2026-06-18 17:36
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0015_create_process_step"),)

    operations = (
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.CharField(
                default="", help_text="Short, problem-oriented excerpt shown on project cards.", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="summary_en",
            field=models.CharField(
                help_text="Short, problem-oriented excerpt shown on project cards.", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="summary_es",
            field=models.CharField(
                help_text="Short, problem-oriented excerpt shown on project cards.", max_length=200, null=True
            ),
        ),
    )
