# Generated by Django 5.2.15 on 2026-06-19 15:15
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0016_project_summary_project_summary_en_and_more"),)

    operations = (
        migrations.AlterField(
            model_name="service",
            name="icon_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— default (check-circle) —"),
                    ("code", "Code"),
                    ("server", "Server"),
                    ("lightning", "Lightning"),
                    ("chat", "Chat"),
                    ("globe", "Globe"),
                    ("briefcase", "Briefcase"),
                    ("chart", "Chart"),
                    ("shield", "Shield"),
                ],
                max_length=100,
            ),
        ),
    )
