# Generated by Django 5.2.15 on 2026-06-19 16:16
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0017_alter_service_icon_name"),)

    operations = (
        migrations.AlterField(
            model_name="processstep",
            name="icon_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— default (check-circle) —"),
                    ("code", "Code"),
                    ("server", "Server"),
                    ("lightning", "Lightning"),
                    ("chat", "Chat"),
                    ("globe", "Globe"),
                    ("briefcase", "Briefcase"),
                    ("chart", "Chart"),
                    ("shield", "Shield"),
                    ("search", "Search"),
                    ("clock", "Clock"),
                    ("cog", "Cog"),
                    ("pencil", "Pencil"),
                    ("sparkles", "Sparkles"),
                    ("eye", "Eye"),
                    ("phone", "Phone"),
                    ("document", "Document"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "— default (check-circle) —"),
                    ("code", "Code"),
                    ("server", "Server"),
                    ("lightning", "Lightning"),
                    ("chat", "Chat"),
                    ("globe", "Globe"),
                    ("briefcase", "Briefcase"),
                    ("chart", "Chart"),
                    ("shield", "Shield"),
                    ("search", "Search"),
                    ("clock", "Clock"),
                    ("cog", "Cog"),
                    ("pencil", "Pencil"),
                    ("sparkles", "Sparkles"),
                    ("eye", "Eye"),
                    ("phone", "Phone"),
                    ("document", "Document"),
                ],
                max_length=100,
            ),
        ),
    )
