# Generated by Django 5.2.15 on 2026-06-25 07:40
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("home", "0018_add_new_icons_and_process_step_icon_choices"),)

    operations = (
        migrations.AddField(
            model_name="personalinfo",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="location_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="location_es",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    )
