# Generated by Django 5.1.4 on 2025-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="BannerConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True)),
                ("title_en", models.CharField(max_length=100, null=True, unique=True)),
                ("title_es", models.CharField(max_length=100, null=True, unique=True)),
                ("text", models.CharField(max_length=200)),
                ("text_en", models.CharField(max_length=200, null=True)),
                ("text_es", models.CharField(max_length=200, null=True)),
                ("show_banner", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CookieGroup",
            fields=[
                ("cookie_id", models.CharField(max_length=50, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("name_en", models.CharField(max_length=50, null=True)),
                ("name_es", models.CharField(max_length=50, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
                ("is_required", models.BooleanField()),
            ],
        ),
    )
