# Generated by Django 5.1.5 on 2025-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("cookie_consent", "0002_cookiegroup_version"),)

    operations = (
        migrations.AlterField(
            model_name="cookiegroup",
            name="version",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    )
