# Generated by Django 5.2.8 on 2026-01-14 20:29
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("contact", "0001_initial"),)

    operations = (
        migrations.AddField(
            model_name="contactmessage",
            name="recaptcha_score",
            field=models.FloatField(blank=True, null=True),
        ),
    )
