# Generated by Django 5.2.15 on 2026-06-15 09:40
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("base", "0005_sitemedia"),
        ("contact", "0002_contactmessage_recaptcha_score"),
    )

    operations = (
        migrations.CreateModel(
            name="ContactPrivacyNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "legal_and_privacy",
                    models.ForeignKey(
                        blank=True,
                        help_text=(
                            "Legal and Privacy section used as the contact form's privacy policy. "
                            "If empty, no consent checkbox is shown."
                        ),
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="base.legalandprivacy",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    )
