# Generated by Django 5.2.15 on 2026-06-15 11:00
from __future__ import annotations

from django.db import migrations, models

import utils.fields


class Migration(migrations.Migration):
    dependencies = (("contact", "0003_contactprivacynotice"),)

    operations = (
        migrations.RenameModel(
            old_name="ContactPrivacyNotice",
            new_name="ContactFormConfiguration",
        ),
        migrations.AddField(
            model_name="contactformconfiguration",
            name="email_provider",
            field=models.CharField(
                choices=[("smtp", "SMTP"), ("brevo_api", "Brevo API")],
                default="smtp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactformconfiguration",
            name="default_from_email",
            field=models.EmailField(default="noreply@localhost", max_length=254),
        ),
        migrations.AddField(
            model_name="contactformconfiguration",
            name="contact_email",
            field=models.EmailField(default="contact@localhost", max_length=254),
        ),
        migrations.AddField(
            model_name="contactformconfiguration",
            name="provider_config",
            field=utils.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Provider-specific settings, encrypted at rest. For SMTP: host, port, use_tls, "
                    "use_ssl, username, password, timeout. For Brevo API: api_key."
                ),
            ),
        ),
    )
