# Generated by Django 5.2.15 on 2026-06-21 08:11
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (("contact", "0004_contactformconfiguration"),)

    operations = (
        migrations.AddField(
            model_name="contactformconfiguration",
            name="intro",
            field=models.TextField(
                blank=True, help_text="Text shown above the contact form. Leave empty to use the default."
            ),
        ),
        migrations.AddField(
            model_name="contactformconfiguration",
            name="intro_en",
            field=models.TextField(
                blank=True, help_text="Text shown above the contact form. Leave empty to use the default.", null=True
            ),
        ),
        migrations.AddField(
            model_name="contactformconfiguration",
            name="intro_es",
            field=models.TextField(
                blank=True, help_text="Text shown above the contact form. Leave empty to use the default.", null=True
            ),
        ),
    )
