# Generated by Django 5.2.15 on 2026-06-25 09:25
from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = (
        ("contact", "0005_add_intro_to_contact_form_configuration"),
        ("home", "0019_personalinfo_location"),
    )

    operations = (
        migrations.AddField(
            model_name="contactmessage",
            name="budget_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_1k", "Under €1,000"),
                    ("1k_5k", "€1,000 \u2013 €5,000"),
                    ("5k_15k", "€5,000 \u2013 €15,000"),
                    ("over_15k", "Over €15,000"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="service_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_messages",
                to="home.service",
            ),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="timeline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_1m", "Less than 1 month"),
                    ("1m_3m", "1 \u2013 3 months"),
                    ("3m_6m", "3 \u2013 6 months"),
                    ("over_6m", "6+ months"),
                ],
                max_length=20,
            ),
        ),
    )
