"""
Django settings for personal-portfolio project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from __future__ import annotations

import os
from pathlib import Path

import dj_database_url
import django_stubs_ext
import environ  # type: ignore[import-untyped]
from django.utils.translation import gettext_lazy as _

# Monkeypatching Django, so stubs will work for all generics,
# see: https://github.com/typeddjango/django-stubs
django_stubs_ext.monkeypatch()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=str,
    ALLOWED_HOSTS=(str, ""),
    MAINTENANCE_MODE=(bool, False),
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")
ALLOWED_HOSTS = env("ALLOWED_HOSTS").split(" ")
MAINTENANCE_MODE = env("MAINTENANCE_MODE")
CSRF_TRUSTED_ORIGINS = [f"https://{allowed_host}" for allowed_host in ALLOWED_HOSTS]

DATABASES = {
    "default": dj_database_url.config(
        default=env("DATABASE_URL"),
        conn_max_age=600,
    )
}


# Application definition
INSTALLED_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "solo",
    "adminsortable2",
    "imagekit",
    "modeltranslation",
    "django_cotton",
    "django_cooco",
    "anymail",
    "base",
    "cookie_consent",
    "home",
    "contact",
)

MIGRATION_MODULES = {
    "cooco": "third_party.django_cooco.migrations",
}

MODELTRANSLATION_TRANSLATION_FILES = ("third_party.django_cooco.translation",)


MIDDLEWARE = [
    "core.middleware.MaintenanceModeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = (
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": (),
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
            ],
            "libraries": {
                "filters": "core.templatetags.filters",
            },
        },
    },
)

WSGI_APPLICATION = "core.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = (
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
)


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = (
    ("en", _("English")),
    ("es", _("Spanish")),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

STATIC_URL = "/static/"
STATICFILES_DIRS = (BASE_DIR / "static",)
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"


LOCALE_PATHS = (BASE_DIR / "locale/",)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

COOCO_COOKIE_NAME = "cookie_consent"

TEST_RUNNER = "utils.test_utils.custom_test_runner.CustomTestRunner"

COTTON_BASE_DIR = BASE_DIR / "core"

# Email Configuration for the contact form
# The actual provider (SMTP or Brevo API) and its credentials are configured
# via the ContactFormConfiguration singleton in the admin.

if DEBUG:
    # In development, print emails to console
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "contact.email_backend.DatabaseEmailBackend"

# Symmetric key used to encrypt provider credentials stored in the database.
FIELD_ENCRYPTION_KEY = env("FIELD_ENCRYPTION_KEY")

if DEBUG:
    CACHE_MIDDLEWARE_SECONDS = 0

# Google reCAPTCHA v3 Configuration
RECAPTCHA_SITE_KEY = env("RECAPTCHA_SITE_KEY", default=None)
RECAPTCHA_SECRET_KEY = env("RECAPTCHA_SECRET_KEY", default=None)
RECAPTCHA_SCORE_THRESHOLD = env.float("RECAPTCHA_SCORE_THRESHOLD", default=0.5)

IS_RECAPTCHA_CONFIGURED = bool(RECAPTCHA_SITE_KEY) and bool(RECAPTCHA_SECRET_KEY)

# Logging
# https://docs.djangoproject.com/en/5.1/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
        "json": {
            "()": "core.logging.JsonFormatter",
        },
    },
    "handlers": {
        "stdout": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
            "formatter": "console" if DEBUG else "json",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["stdout"],
            "level": "INFO",
            "propagate": False,
        },
        "contact": {
            "handlers": ["stdout"],
            "level": "INFO",
            "propagate": False,
        },
        "recaptcha": {
            "handlers": ["stdout"],
            "level": "INFO",
            "propagate": False,
        },
        "security": {
            "handlers": ["stdout"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
