name: Node Setup

inputs:
  node-version:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Set up Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      shell: bash
      run: npm install
